create table if not exists public.photo_likes (
    id bigint generated by default as identity primary key,
    photo_path text not null,
    voter_id text not null,
    full_name text not null default 'Guest',
    created_at timestamptz not null default now(),
    unique (photo_path, voter_id)
);

alter table public.photo_likes
    add column if not exists full_name text not null default 'Guest';

create index if not exists photo_likes_photo_path_idx
    on public.photo_likes (photo_path);

alter table public.photo_likes enable row level security;

drop policy if exists "Anyone can read photo likes" on public.photo_likes;
create policy "Anyone can read photo likes"
    on public.photo_likes for select
    to anon, authenticated
    using (true);

drop policy if exists "Anyone can add photo likes" on public.photo_likes;
create policy "Anyone can add photo likes"
    on public.photo_likes for insert
    to anon, authenticated
    with check (length(photo_path) > 0 and length(voter_id) > 0 and length(full_name) between 2 and 64);

drop policy if exists "Anyone can remove their photo likes" on public.photo_likes;
create policy "Anyone can remove their photo likes"
    on public.photo_likes for delete
    to anon, authenticated
    using (length(photo_path) > 0 and length(voter_id) > 0);

grant select, insert, delete on public.photo_likes to anon, authenticated;
grant usage, select on sequence public.photo_likes_id_seq to anon, authenticated;
